/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.clientefvgames.vista;

import com.mycompany.clientefvgames.Cliente;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import javax.swing.*;

/**
 *
 * @author Melvin Prendas
 */
public class PanelAgregarCliente extends javax.swing.JPanel {

    private JTextField nombreField, apellidoField, cedulaField, direccionField, emailField, contrasenaField, saldoField;

    public PanelAgregarCliente() {
        setLayout(new GridLayout(8, 2));

        // Crear y añadir los campos y etiquetas
        add(new JLabel("Nombre:"));
        nombreField = new JTextField();
        add(nombreField);

        add(new JLabel("Apellido:"));
        apellidoField = new JTextField();
        add(apellidoField);

        add(new JLabel("Cédula:"));
        cedulaField = new JTextField();
        add(cedulaField);

        add(new JLabel("Dirección:"));
        direccionField = new JTextField();
        add(direccionField);

        add(new JLabel("Email:"));
        emailField = new JTextField();
        add(emailField);

        add(new JLabel("Contraseña:"));
        contrasenaField = new JTextField();
        add(contrasenaField);

        add(new JLabel("Saldo:"));
        saldoField = new JTextField();
        add(saldoField);

        // Botón para agregar cliente
        JButton agregarButton = new JButton("Agregar Cliente");
        agregarButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Aquí se implementará la lógica para enviar el cliente al servidor
                String nombre = nombreField.getText();
                String apellido = apellidoField.getText();
                String cedula = cedulaField.getText();
                String direccion = direccionField.getText();
                String email = emailField.getText();
                String contrasena = contrasenaField.getText();
                double saldo = Double.parseDouble(saldoField.getText());
                // Crear un objeto Cliente
                Cliente nuevoCliente = new Cliente(nombre, apellido, cedula, direccion, email, contrasena, saldo);
                

                try (Socket socket = new Socket("localhost", 12345);
                ObjectOutputStream out = new ObjectOutputStream(socket.getOutputStream());
                ObjectInputStream in = new ObjectInputStream(socket.getInputStream())) {

                // Enviar solicitud al servidor/
                out.writeObject("AGREGAR_CLIENTE");
                System.out.println("Enviando objeto Cliente: " + nuevoCliente);
                out.writeObject(nuevoCliente);
                System.out.println("Objeto Cliente enviado");
                out.flush();
                

                // Recibir la respuesta del servidor
                String response = (String) in.readObject();
                JOptionPane.showMessageDialog(null, response);

                } catch (IOException | ClassNotFoundException ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Error al conectar con el servidor: " + ex.getMessage());
                }
                    }
                });
        add(agregarButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
