/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.clientefvgames.vista;
import com.mycompany.fvgames.modelo.Compra;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.List;
/**
 *
 * @author Melvin Prendas
 */
public class PanelComprasRealizadas extends JPanel {
    private JButton verComprasButton;
    private JTextArea comprasArea;

    public PanelComprasRealizadas() {
        setLayout(new BorderLayout(10, 10));

        verComprasButton = new JButton("Ver Compras Realizadas");
        comprasArea = new JTextArea();
        comprasArea.setEditable(false);
        JScrollPane scrollPane = new JScrollPane(comprasArea);

        add(verComprasButton, BorderLayout.NORTH);
        add(scrollPane, BorderLayout.CENTER);

        // Acción del botón "Ver Compras Realizadas"
        verComprasButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                verComprasRealizadas();
            }
        });
    }

    private void verComprasRealizadas() {
        try {
            // Enviar solicitud para ver las compras realizadas
            Socket socket = new Socket("localhost", 12345); // Ajusta la IP y puerto según sea necesario
            ObjectOutputStream out = new ObjectOutputStream(socket.getOutputStream());
            ObjectInputStream in = new ObjectInputStream(socket.getInputStream());

            out.writeObject("OBTENER_COMPRAS");
            out.flush();

            // Recibir la lista de compras realizadas
            List<Compra> compras = (List<Compra>) in.readObject();

            // Mostrar las compras en el área de texto
            comprasArea.setText("");
            for (Compra compra : compras) {
                comprasArea.append("ID del producto: " + compra.getId() + ", ID del Cliente: " + compra.getIdCliente() +
                         ", Fecha: " + compra.getFecha().toString() + ", Cantidad: " + compra.getCantidad() + "\n");
            }

            in.close();
            out.close();
            socket.close();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al ver las compras realizadas: " + ex.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
