/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.clientefvgames.vista;

import com.mycompany.fvgames.modelo.Compra;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;

/**
 *
 * @author Melvin Prendas
 */
public class PanelAgregarCompra extends javax.swing.JPanel {

    private JTextField idClienteField;
    private JTextField idProductoField;
    private JTextField cantidadField;
    private JButton agregarCompraButton;

    public PanelAgregarCompra() {
        setLayout(new GridLayout(4, 2, 10, 10));

        JLabel idClienteLabel = new JLabel("ID Cliente:");
        idClienteField = new JTextField();

        JLabel idProductoLabel = new JLabel("ID Producto:");
        idProductoField = new JTextField();

        JLabel cantidadLabel = new JLabel("Cantidad:");
        cantidadField = new JTextField();

        agregarCompraButton = new JButton("Agregar Compra");

        add(idClienteLabel);
        add(idClienteField);
        add(idProductoLabel);
        add(idProductoField);
        add(cantidadLabel);
        add(cantidadField);
        add(new JLabel()); // empty cell for spacing
        add(agregarCompraButton);

        // Acción del botón
        agregarCompraButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                agregarCompra();
            }
        });
    }

    private void agregarCompra() {
        try {
            int idCliente = Integer.parseInt(idClienteField.getText());
            int idProducto = Integer.parseInt(idProductoField.getText());
            int cantidad = Integer.parseInt(cantidadField.getText());

            // Creas una compra, asignándole el id del cliente y el id del producto
            Compra nuevaCompra = new Compra(idCliente, idProducto, cantidad);

            // Envío de la compra al servidor
            Socket socket = new Socket("localhost", 12345); // Ajusta la IP y puerto según sea necesario
            ObjectOutputStream out = new ObjectOutputStream(socket.getOutputStream());

            out.writeObject("AGREGAR_COMPRA");
            out.writeObject(nuevaCompra);

            // Respuesta del servidor
            ObjectInputStream in = new ObjectInputStream(socket.getInputStream());
            String respuesta = (String) in.readObject();
            JOptionPane.showMessageDialog(this, respuesta);

            in.close();
            out.close();
            socket.close();

            // Limpiar los campos después de agregar la compra
            idClienteField.setText("");
            idProductoField.setText("");
            cantidadField.setText("");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al agregar la compra: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
