/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.clientefvgames.vista;
import com.mycompany.clientefvgames.Producto;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
/**
 *
 * @author Melvin Prendas
 */
public class PanelAgregarProducto extends javax.swing.JPanel {

    private JTextField nombreField;
    private JTextField categoriaField;
    private JTextField precioField;
    private JTextField cantidadField;
    private JButton agregarButton;

    public PanelAgregarProducto() {
        setLayout(new GridLayout(5, 2, 10, 10));

        JLabel nombreLabel = new JLabel("Nombre:");
        nombreField = new JTextField();

        JLabel categoriaLabel = new JLabel("Categoría:");
        categoriaField = new JTextField();

        JLabel precioLabel = new JLabel("Precio:");
        precioField = new JTextField();

        JLabel cantidadLabel = new JLabel("Cantidad:");
        cantidadField = new JTextField();

        agregarButton = new JButton("Agregar Producto");

        add(nombreLabel);
        add(nombreField);
        add(categoriaLabel);
        add(categoriaField);
        add(precioLabel);
        add(precioField);
        add(cantidadLabel);
        add(cantidadField);
        add(new JLabel()); // empty cell for spacing
        add(agregarButton);

        // Acción del botón
        agregarButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                agregarProducto();
            }
        });
    }

    private void agregarProducto() {
        try {
            String nombre = nombreField.getText();
            String categoria = categoriaField.getText();
            double precio = Double.parseDouble(precioField.getText());
            int cantidad = Integer.parseInt(cantidadField.getText());

            Producto nuevoProducto = new Producto(nombre, categoria, precio, cantidad);

            // Envío del producto al servidor
            Socket socket = new Socket("localhost", 12345); // Ajusta la IP y puerto según sea necesario
            ObjectOutputStream out = new ObjectOutputStream(socket.getOutputStream());

            out.writeObject("AGREGAR_PRODUCTO");
            out.writeObject(nuevoProducto);

            // Respuesta del servidor
            ObjectInputStream in = new ObjectInputStream(socket.getInputStream());
            String respuesta = (String) in.readObject();
            JOptionPane.showMessageDialog(this, respuesta);

            in.close();
            out.close();
            socket.close();

            // Limpiar los campos después de agregar
            nombreField.setText("");
            categoriaField.setText("");
            precioField.setText("");
            cantidadField.setText("");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al agregar el producto: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
